version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: reservations
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .  # Construit l'image à partir du Dockerfile présent dans le même dossier
    container_name: reservations-app
    depends_on:
      - db
    environment:
      # Remplacez "db" par le nom du service défini dans docker-compose.yml
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/reservations?autoreconnect=true&useSSL=false&serverTimezone=Europe/Brussels&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    ports:
      - "8080:8080"

volumes:
  db_data:
