INSERT INTO `artists` (`id`, `firstname`, `lastname`, `troupe_id`)
VALUES (1, 'Daniel', 'Marcelin', 1),
       (2, 'Philippe', 'Laurent', 2),
       (3, 'Marius', 'Von Mayenburg', 3),
       (4, 'Olivier', 'Boudon', 4),
       (5, 'Anne Marie', 'Loop', 1),
       (6, 'Pietro', 'Varasso', 2),
       (7, 'Laurent', 'Caron', 3),
       (8, 'Élena', 'Perez', 4),
       (9, 'Guillaume', 'Alexandre', 1),
       (10, 'Claude', 'Semal', 2),
       (11, 'Laurence', 'Warin', 3),
       (12, 'Pierre', 'Wayburn', 4),
       (13, 'Gwendoline', 'Gauthier', 1),
       (14, 'Jacques', 'Brel', 2),
       (15, 'Salvatore', 'Adamo', 3),
       (16, 'Stromae', 'Cowboy', 4),
       (17, 'Angèle', 'Van Laeken', 1),
       (18, 'Arno', 'Hintjens', 2),
       (19, 'Alex', 'Callier', 3),
       (20, 'Wouter', 'De Backer', 4),
       (21, 'Jean', 'Dupont', 1),
       (22, 'Marie', 'Martin', 2),
       (23, 'Paul', 'Moreau', 3),
       (24, 'Sophie', 'Lefèvre', 4),
       (25, 'Antoine', 'Petit', 1),
       (26, 'Claire', 'Laurent', 2),
       (27, 'Nicolas', 'Roche', 3),
       (28, 'Émilie', 'Dubois', 4),
       (29, 'Guillaume', 'Durand', 1),
       (30, 'Camille', 'Leroy', 2),
       (31, 'Jan', 'De Vries', 3),
       (32, 'Piet', 'Janssen', 4),
       (33, 'Karel', 'De Bruin', 1),
       (34, 'Femke', 'Visser', 2),
       (35, 'Bram', 'Smit', 3),
       (36, 'Sanne', 'Bakker', 4),
       (37, 'Tom', 'Verhoeven', 1),
       (38, 'Lotte', 'De Wit', 2),
       (39, 'Daan', 'Van Dijk', 3),
       (40, 'Emma', 'De Lange', 4),
       (41, 'Michael', 'Smith', 1),
       (42, 'Jennifer', 'Johnson', 2),
       (43, 'William', 'Brown', 3),
       (44, 'Elizabeth', 'Davis', 4),
       (45, 'James', 'Wilson', 1),
       (46, 'Mary', 'Taylor', 2),
       (47, 'Robert', 'Anderson', 2),
       (48, 'Patricia', 'Thomas', 3),
       (49, 'David', 'Jackson', 4),
       (50, 'Linda', 'White', 1),
       (51, 'Martin', 'Robinson', 2),
       (52, 'Sophie', 'Edwards', 3),
       (53, 'Alexandre', 'Bernard', 4),
       (54, 'Chloé', 'Fontaine', 1),
       (55, 'Laurent', 'Marchand', 2),
       (56, 'Isabelle', 'Garnier', 3),
       (57, 'Sébastien', 'Girard', 4),
       (58, 'Manon', 'Petitjean', 1),
       (59, 'Olivier', 'Dupuis', 2),
       (60, 'Juliette', 'Renault', 3),
       (61, 'Hugo', 'Rousseau', 4);
